### ISSUE TITLE
Debug builds and release builds with debug info

### ISSUE THREAD

**Issue by docbrownx** [bastibe/libsndfile-binaries#18]
Can we get Debug and RelWithDebInfo builds please?  These would be really awesome to have!!  I'd like to build locally but wrangling dependencies with such a small team is difficult, and we'd love to be able to help with fixes if we could debug them more easily without having to build locally first.

**Comment by bastibe** [comment]
The point of this repository is to provide binaries for python-soundfile. As such, I don't intend to provide debug builds or alternative build scripts. That said, feel free to fork this repository and modify the CI scripts for your application. Since this is using the Github CI, it should run perfectly in your fork.
