### ISSUE TITLE
Win64: can we remove dependency to vcruntime140.dll ?

### ISSUE THREAD

**Issue by Lulu04** [bastibe/libsndfile-binaries#27]
Hi, thank you to share the pre-compiled binaries!

I wrote a software that use LibSndFile and downloaded the Win64 DLL from here. All work fine on the (Windows 10) computer where I developed the software, but a problem appears when I tryed it on another computer Windows 7 64b:
"VCRUNTIME140.DLL missing..." appears at app startup and LibSndFile is not opened.

After some researchs, I found on the net that one have to install "Microsoft Visual Studio ++ 2015" both x64 and x86 version from [**here**](https://www.microsoft.com/en-us/download/details.aspx?id=52685)
After installing this, all work fine on the new computer.

Since I plan to deploy my app, it's not convenient to ask the users to install this library. I'm not familiar with C.
My questions are:

1) This dependency is here because you have compiled the lib with msvc ?
2) Is there a way to avoid this dependency? may be compiling the lib with another compiler like mingw-w64 from [**here**](https://github.com/niXman/mingw-builds-binaries/releases/tag/13.1.0-rt_v11-rev1) ?
3) if Yes, which version of mingw-w64 should I use?

Thank you in advance.
Regards

Edit: a workaround is to include the dll to my executable, since its size is only 106k. But I'm still curious about the answers to the above questions :)

**Comment by bastibe** [comment]
The vcruntime DLL is a necessary dependency when using the MSVC compiler. There's no way around it. This project compiles Libsndfile binaries for use in python-soundfile, which has specific compiler requirements on Windows, that mandate the use of MSVC.

Much as I love the GCC toolchain on Unixes, its Windows ports are regrettably limited. MinGW is maintained only by a very skeleton crew, and not entirely C-standard compliant, and libraries are not 100% compatible with MSVC-compiled binaries. Thus, if interop with MSVC-compiled code is required, use the MSVC compiler. Python, in this instance, is MSVC-compiled, which is why this repository compiles with MSVC as well.

**Comment by Lulu04** [comment]
Sorry for my late reply and thank you for your clear explanation. I will distribute the dll with my binary.
Regards
